export {default as Home } from './Home'
export {default as About } from './About'
export {default as Contact } from './Contact'
export {default as Teacher } from './Teacher'
export {default as Nopage } from './Nopage'
export {default as Courses } from './Courses'